apiVersion: v1
kind: Service
metadata:
  name: pythonflaskservice-loadbalancer
  labels:
    app: pythonflaskservice-app
spec:
  type: LoadBalancer
  selector:
    app: pythonflaskservice-app
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443