apiVersion: v1
kind: Service
metadata:
  name: pythonflaskservice-nodeport
  labels:
    app: pythonflaskservice-app
spec:
  type: NodePort
  selector:
    app: pythonflaskservice-app
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443